// Public Key Actions
export const PUBLIC_KEY_GET_REQUEST = "PUBLIC_KEY_GET_REQUEST";
export const PUBLIC_KEY_GET_SUCCESS = "PUBLIC_KEY_GET_SUCCESS";
export const PUBLIC_KEY_GET_FAILURE = "PUBLIC_KEY_GET_FAILURE";

// User Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Employees Actions
export const EMPLOYEES_LIST_REQUEST = "EMPLOYEES_LIST_REQUEST";
export const EMPLOYEES_LIST_SUCCESS = "EMPLOYEES_LIST_SUCCESS";
export const EMPLOYEES_LIST_FAILURE = "EMPLOYEES_LIST_FAILURE";
export const EMPLOYEE_ADD_REQUEST = "EMPLOYEE_ADD_REQUEST";
export const EMPLOYEE_ADD_SUCCESS = "EMPLOYEE_ADD_SUCCESS";
export const EMPLOYEE_ADD_FAILURE = "EMPLOYEE_ADD_FAILURE";
