// Public Key Actions
export const PUBLIC_KEY_GET_REQUEST = "PUBLIC_KEY_GET_REQUEST";
export const PUBLIC_KEY_GET_SUCCESS = "PUBLIC_KEY_GET_SUCCESS";
export const PUBLIC_KEY_GET_FAILURE = "PUBLIC_KEY_GET_FAILURE";

// User Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
